[課題のURL](https://diver.diveintocode.jp/curriculums/1630)

# Week2授業前課題3 行列積のスクラッチ

# 【問題1】行列積を手計算する

In [4]:
import numpy as np

下記の"通常の行列の積"を参照

[参考情報wiki](https://ja.wikipedia.org/wiki/行列の乗法)

In [29]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#print(a_ndarray)
#print(b_ndarray)

#print( a_ndarray[0] )
#print( b_ndarray[:,0] )
#print( a_ndarray[0] * b_ndarray[:,0] )
#print( sum( a_ndarray[0] * b_ndarray[:,0] ) )

a00 = sum( a_ndarray[0] * b_ndarray[:,0] )
a01 = sum( a_ndarray[0] * b_ndarray[:,1] )
a02 = sum( a_ndarray[0] * b_ndarray[:,2] )
a10 = sum( a_ndarray[1] * b_ndarray[:,0] )
a11 = sum( a_ndarray[1] * b_ndarray[:,1] )
a12 = sum( a_ndarray[1] * b_ndarray[:,2] )
a20 = sum( a_ndarray[2] * b_ndarray[:,0] )
a21 = sum( a_ndarray[2] * b_ndarray[:,1] )
a22 = sum( a_ndarray[2] * b_ndarray[:,2] )

ab_ndarray = np.array( np.array([[a00, a01, a02], [a10, a11, a12], [a20, a21, a22]]) )

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題2】NumPyの関数による計算

- np.matmul()を使った場合

In [3]:
ab_ndarray = np.matmul(a_ndarray, b_ndarray)

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


- np.dot()を使った場合

In [31]:
ad_ndarray = np.dot(a_ndarray, b_ndarray)

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


- @演算子を使った場合

In [33]:
ad_ndarray = a_ndarray @ b_ndarray

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題3】ある要素の計算を実装

In [81]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

#print(a_ndarray)
#print(b_ndarray)

#print( a_ndarray[0] )
#print( b_ndarray[:,0] )
#print( a_ndarray[0] * b_ndarray[:,0] )
#print( sum( a_ndarray[0] * b_ndarray[:,0] ) )

a00 = sum( a_ndarray[0] * b_ndarray[:,0] )
a01 = sum( a_ndarray[0] * b_ndarray[:,1] )
a02 = sum( a_ndarray[0] * b_ndarray[:,2] )
a10 = sum( a_ndarray[1] * b_ndarray[:,0] )
a11 = sum( a_ndarray[1] * b_ndarray[:,1] )
a12 = sum( a_ndarray[1] * b_ndarray[:,2] )
a20 = sum( a_ndarray[2] * b_ndarray[:,0] )
a21 = sum( a_ndarray[2] * b_ndarray[:,1] )
a22 = sum( a_ndarray[2] * b_ndarray[:,2] )

ab_ndarray = np.array( np.array([[a00, a01, a02], [a10, a11, a12], [a20, a21, a22]]) )

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題4】行列積を行う関数の作成

In [82]:
#  3*3の行列積を算出する
def calc_multi( a_ndarray, b_ndarray ):

    list_num = []
    ab_ndarray = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    
    for i in range(3):
        for j in range(3):
        
            #print(i, j)
            list_num.append(sum( a_ndarray[i] * b_ndarray[:,j] ))
            
    ab_ndarray = np.array(list_num).reshape((3,3))
    
    return ab_ndarray

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

ab_ndarray = calc_multi(a_ndarray, b_ndarray)

print(ab_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 【問題5】計算が定義されない入力を判定する

In [83]:
# 3*3の行列積を算出する
# 例外処理付き
def calc_multi_check( a_ndarray, b_ndarray ):

    list_num = []
    ab_ndarray = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
    
    if len(a_ndarray[0]) != len(b_ndarray[:,0]):
        print("行列積は引数1の列数と引数2の行数が等しい場合に定義されます")
        print("引数を確認してください")
    else:
        for i in range(3):
            for j in range(3):
        
                #print(i, j)
                list_num.append(sum( a_ndarray[i] * b_ndarray[:,j] ))
            
        ab_ndarray = np.array(list_num).reshape((3,3))
    
    return ab_ndarray

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

#print(len(d_ndarray[0]))

de_ndarray = calc_multi_check(d_ndarray, e_ndarray)


行列積は引数1の列数と引数2の行数が等しい場合に定義されます
引数を確認してください


# 【問題5】転置

np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [109]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 転置
a_ndarrayT = np.transpose(a_ndarray)
b_ndarrayT = b_ndarray.T

# 行列積
print("転置の行列積(bt*at)")
print(b_ndarrayT@a_ndarrayT)

print("転置の行列積(bt*at)の転置")
print((b_ndarrayT@a_ndarrayT).T)

print("参考:行列積a*b")
print(a_ndarray@b_ndarray)

転置の行列積(bt*at)
[[  6  12 -18]
 [ 29  52 -51]
 [-20  38 -48]]
転置の行列積(bt*at)の転置
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
参考:行列積a*b
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
