[課題のURL](https://diver.diveintocode.jp/curriculums/1639)

# Week4授業前課題3 オブジェクト指向の活用

* 【問題1】これまで利用してきたクラスの列挙

Pandas:DataFrameなど
matplotlib:figureなど
scikit-learn:LogisticRegressionなど

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

* これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

メソッド  
*numpyのreshape,    
*pandasのsort, read_csv, head, info
  
インスタンス変数  
*numpyのshape, dtype, size  
*pandasのcolumns, index, 

# 【問題3】標準化クラスをスクラッチで作成

In [26]:
import numpy as np

class ScratchStandardScaler( ):
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        # 標準化のために平均と標準偏差を計算して、記憶する
        # 引数:X : 次の形のndarray, shape (n_samples, n_features)
    
        self.mean_ = np.mean(X, axis = 0)
        self.var_ = np.var(X, axis = 0) # 分散
        self.std_ = np.std(X, axis = 0) # 標準偏差
        
        pass
    def transform(self, X):
        # fitで求めた平均と標準偏差を利用し標準化を行う。
        # 引数:X : 次の形のndarray, shape (n_samples, n_features)
        # 戻り値:次の形のndarray, shape (n_samples, n_features)  標準化された特緒量
        
        X_scaled = (X - self.mean_)/self.std_
        
        pass
        return X_scaled

In [27]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
#print("分散 : {}".format(scratch_scaler.var_))
#print("標準偏差 : {}".format(scratch_scaler.std_))
X_std = scratch_scaler.transform(X)
print("標準化")
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
標準化
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [28]:
# 確認用
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

print("平均 : {}".format(scaler.mean_))
#print("分散 : {}".format(scaler.std_))
X_test = scratch_scaler.transform(X)
print("標準化")
print(X_test)

平均 : [4.86 3.31 1.45 0.22]
標準化
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


# 【問題4】 四則演算を行うクラスの作成

引き算、掛け算、割り算のメソッドを加えてください  
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。  
クラス名や説明文も適切に書き換えてください。

In [55]:
class CalcClass():
    """
    四則演算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def _judge(self, value):
        if (type(value) is int) or (type(value) is float):
            self.value = value
            print("初期値{}が設定されました".format(self.value))
            result = 1 # TRUE
        else:
            print("引数の型が違います。")
            print("int型かfloat型に変更してください")
            result = 0 # FALSE

        return result
    
    def __init__(self, value):        
        # 型の確認
        self._judge(value)
            
    def add(self, value):
        # 型の確認
        result = self._judge(value)
        if result == 1:
            # self.valueと引数を加算
            self.value = self.value + value

    def sub(self, value):
        # 型の確認
        result = self._judge(value)
        if result == 1:        
            # self.valueと引数を減算
            self.value = self.value - value

    def multi(self, value):
        # 型の確認
        result = self._judge(value)
        if result == 1:
            # self.valueと引数を乗数
            self.value = self.value * value
        
    def divi(self, value):
        # 型の確認
        result = self._judge(value)
        if result == 1:
            # self.valueと引数を除算
            self.value = self.value / value

In [56]:
example = CalcClass([1,1])
example = CalcClass("str")
example = CalcClass(0.1)
example = CalcClass(5)

example.add(3)
print("value : {}".format(example.value))

example.sub(1)
print("value : {}".format(example.value))

example.multi(2)
print("value : {}".format(example.value))

example.divi(7)
print("value : {}".format(example.value))

example.add("a")
example.sub("a")
example.multi("a")
example.divi("a")

引数の型が違います。
int型かfloat型に変更してください
引数の型が違います。
int型かfloat型に変更してください
初期値0.1が設定されました
初期値5が設定されました
初期値3が設定されました
value : 6
初期値1が設定されました
value : 0
初期値2が設定されました
value : 4
初期値7が設定されました
value : 1.0
引数の型が違います。
int型かfloat型に変更してください
引数の型が違います。
int型かfloat型に変更してください
引数の型が違います。
int型かfloat型に変更してください
引数の型が違います。
int型かfloat型に変更してください
