[課題のURL](https://diver.diveintocode.jp/curriculums/1639)

# Week4授業前課題3 オブジェクト指向の活用

* 【問題1】これまで利用してきたクラスの列挙

Pandas:DataFrameなど
matplotlib:figureなど
scikit-learn:LogisticRegressionなど

# 【問題2】これまで利用してきたメソッドやインスタンス変数の列挙

* これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。

最低でもそれぞれ5つ以上答えてください。

メソッド  
*numpyのreshape,    
*pandasのsort, read_csv, head, info
  
インスタンス変数  
*numpyのshape, dtype, size  
*pandasのcolumns, index, 

# 【問題3】標準化クラスをスクラッチで作成

In [41]:
import numpy as np

class ScratchStandardScaler( ):
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        # 標準化のために平均と標準偏差を計算して、記憶する
        # 引数:X : 次の形のndarray, shape (n_samples, n_features)
    
        self.mean_ = np.mean(X, axis = 0)
        self.var_ = np.var(X, axis = 0)
        pass
    def transform(self, X):
        # fitで求めた平均と標準偏差を利用し標準化を行う。
        # 引数:X : 次の形のndarray, shape (n_samples, n_features)
        # 戻り値:次の形のndarray, shape (n_samples, n_features)  標準化された特緒量
        
        X = (X - self.mean_)/self.var_
        X_scaled = X
        
        pass
        return X_scaled

In [42]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


In [43]:
# 確認用
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X)

print("平均 : {}".format(scaler.mean_))
print("分散 : {}".format(scaler.var_))
X_test = scratch_scaler.transform(X)
print(X_test)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


# 【問題4】 四則演算を行うクラスの作成

引き算、掛け算、割り算のメソッドを加えてください  
コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。  
クラス名や説明文も適切に書き換えてください。

In [69]:
class CalcClass():
    """
    四則演算を行うクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        
        if (type(value) is int) or (type(value) is float):
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        else:
            print("引数の型が違います。")
            print("int型かfloat型に変更してください")
                
    def add(self, value):
        # self.valueと引数を加算
        self.value = self.value + value

    def sub(self, value):
        # self.valueと引数を減算
        self.value = self.value - value

    def multi(self, value):
        # self.valueと引数を乗数
        self.value = self.value * value
        
    def divi(self, value):
        # self.valueと引数を除算
        self.value = self.value / value

In [83]:
example = CalcClass([1,1])
example = CalcClass("str")
example = CalcClass(0.1)
example = CalcClass(5)

example.add(3)
print("value : {}".format(example.value))

example.sub(1)
print("value : {}".format(example.value))

example.multi(2)
print("value : {}".format(example.value))

example.divi(7)
print("value : {}".format(example.value))

引数の型が違います。
int型かfloat型に変更してください
引数の型が違います。
int型かfloat型に変更してください
初期値0.1が設定されました
初期値5が設定されました
value : 8
value : 7
value : 14
value : 2.0
